#!/bin/bash

set -e

cd wwv_tones

echo "Generating tone files"
go run main.go

#echo "Converting to MP3s"
#for f in *.wav ; do lame --preset 64 $f ; done
#rm *.wav

echo "Moving to clips directory"
#mv *.mp3 ../clips
mv *.wav ../clips

cd ../clips

echo "Building sprite"
rm output.mp3
audiosprite -f howler2 -e mp3 -b 64 -s 5.02 -u clips *.wav *.mp3
cd ..

echo "Generating sprite layout file"
cat > src/sprite_layout.js <<EOF
/* eslint-disable */
export default
EOF

cat >> src/sprite_layout.js clips/output.json

